spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt-security
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
security:
  jwt:
    access-token:
      name: access_token
      presence.name: access_token_presence
      duration.time.ms: 600000
    refresh-token:
      name: refresh_token
      presence.name: refresh_token_presence
      duration.time.ms: 604800000